name: healsync
description: "HealSync telemedicine UI demo with live ZEGOCLOUD consultations."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  file_picker: ^10.3.2
  google_fonts: ^6.3.2
  http: ^1.5.0
  image_picker: ^1.2.0
  intl: ^0.20.2
  path_provider: ^2.1.5
  pdf: ^3.11.3
  permission_handler: ^12.0.1
  printing: ^5.14.2
  provider: ^6.1.5
  shared_preferences: ^2.5.3
  flutter_tts: ^4.2.2
  speech_to_text: ^7.0.0
  zego_express_engine: ^3.23.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  generate: true
